### DISCUSSION TITLE
Using namespace in JsonProperty annotation

### DISCUSSION THREAD

**Discussion by birolozturkk** [FasterXML/jackson-dataformats-text#486] [Q&A] [answered]
Hi guys I am trying to deserialise my yaml file. I am using @JsonProperty to specify namespace in the fields in my POJO class but this does not work.
I don't want to create a wrapper class for each namespace, do you have a suggestion?

```yaml
language: tr #supported tr, en
database:
  driver: "SQLITE" #MYSQL, SQLITE
  host: "localhost"
  database: "database"
  username: ""
  password: ""
  port: 3306
  useSSL: false
```

```java
@Data
public class Config {

    private String language;

    @JsonProperty("database.driver")
    private String driver;
    @JsonProperty("database.host")
    private String host;
    @JsonProperty("database.database")
    private String database;
    @JsonProperty("database.username")
    private String username;
    @JsonProperty("database.password")
    private String password;
    @JsonProperty("database.port")
    private int port;

    @JsonProperty("database")
    private boolean useSSL;
}
```
  
  
![image](https://github.com/user-attachments/assets/6ebd2bf4-4826-41b0-9a65-58e76d892c02)
