### ISSUE TITLE
setPropertyNamingStrategy doesn't work for YAML

### ISSUE THREAD

**Issue by kuangdev** [FasterXML/jackson-dataformats-text#131]
Goal:
I'd like to use Jackson to parse all the keys in YAML from from camel case to kebab case.

Dependencies:
```xml
<dependency>
      <groupId>com.fasterxml.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-yaml</artifactId>
      <version>2.9.8</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.9.8</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.9</version>
    </dependency>
```
Input Yaml file:
```yaml
cu:
  helloService:
    host: A-service
    maxRetries: 5
```
Real output yaml file:
```yaml
---
cu:
  helloService:
    host: "A-service"
    maxRetries: 5
```
Expected output yaml file
```yaml
cu:
  hello-service:
    host: A-service
    max-retries: 5
```

code
```java
   ObjectMapper objectMapper = new ObjectMapper(new YAMLFactory());
        objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.KEBAB_CASE);
          Object o = objectMapper
                .readValue(new File("./src/test/resources/application-test.yaml"), Object.class);
        objectMapper.writeValue(new File("./src/test/resources/application-test-output.yaml"), o);
```

Not sure by default nothing should happen or not.
