### ISSUE TITLE
Serializing Kotlin data classes produces empty YAML document with Proguard

### ISSUE THREAD

**Issue by AvlWx2014** [FasterXML/jackson-dataformats-text#221]
I'm betting this an issue of misuse, rather than an issue with the API.

I have two data classes as follows:

```kotlin
data class Layout (
        val rowCount: Int,
        val columnCount: Int,
        val layout: List<CellSpec>
)

data class CellSpec (
        val label: String,
        val row: Int,
        val column: Int,
        val height: Int,
        val width: Int
)
```

Which I am serializing to an output file from an Android application like this:

```kotlin
fun write(layout: Layout, file: File): {
    val mapper = ObjectMapper(YAMLFactory()).also {
        it.registerKotlinModule()
    }
    mapper.writeValue(file, layout)
}
```

In `debug` builds, everything works as expected and I get a nice YAML file like this:

```yaml
---
rowCount: 1
columnCount: 4
layout:
- label: "CELL 0"
  row: 0
  column: 0
  height: 1
  width: 1
- label: "CELL 1"
  row: 0
  column: 1
  height: 1
  width: 1
- label: "CELL 2"
  row: 0
  column: 2
  height: 1
  width: 1
- label: "CELL 3"
  row: 0
  column: 3
  height: 1
  width: 1
```

However, once the app is obfuscated with Proguard for `release`, the same code outputs this:
```yaml
--- {}
```

I have added many rules to my `proguard` recommended on the [Jackson On Android](https://github.com/FasterXML/jackson-docs/wiki/JacksonOnAndroid#proguard) page, as well as dependencies recommended by the [Jackson Kotlin Module Caveats](https://github.com/FasterXML/jackson-module-kotlin#caveats).

I'm out of ideas on how to fix this. Could someone help me sort this out?
