### ISSUE TITLE
Nested Yaml question

### ISSUE THREAD

**Issue by sknot-rh** [FasterXML/jackson-dataformats-text#249]
Hi. I was using version 2.10.5 and my code was able to process nested yamls correctly. With version 2.12.2 I am not able to make it work.

Code: 
```
YAMLMapper yamlMapper = new YAMLMapper(new YAMLFactory().enable(YAMLGenerator.Feature.MINIMIZE_QUOTES));
yamlMapper.writerWithDefaultPrettyPrinter().writeValue(new File("output.yaml"), resource.getResource());
```
Output with version 2.10.5
```
---
apiVersion: v1
kind: MyKind
metadata:
  name: example
data:
  config.yaml: |
    lowercaseOutputName: true
    rules:
    - pattern: "metric<name=(.+)><>(\\w+)"
      name: "metric_$1_$2"
      type: "GAUGE"
```
Output with version 2.12.2
```
---
apiVersion: v1
kind: MyKind
metadata:
  name: example
data:
  config.yaml: "lowercaseOutputName:\
    \ true\nrules:\n- pattern: \"metric<name=(.+)><>(\\\\w+)\"\n  name:\
    \ \"metric_$1_$2\"\n  type: \"GAUGE\"\n"
```

Am I missing some serialization option?
