### ISSUE TITLE
[Yaml] Nice list formatting

### ISSUE THREAD

**Issue by PeachesMLG** [FasterXML/jackson-dataformats-text#265]
Is there a way to format a list of objects in yaml better while keeping them as a list code wise? for example
```yml
test:
- a: "a"
  b: 2
  c: "c"
- a: "a"
  b: 2
  c: "c"
- a: "a"
  b: 2
  c: "c"
- a: "a"
  b: 2
  c: "c"
```
would turn into something like
```yml
test:
     1:
          a: "a"
          b: 2
          c: "c"
     2:
          a: "a"
          b: 2
          c: "c"
     3:
          a: "a"
          b: 2
          c: "c"
```
Since its alot easier to read
