### ISSUE TITLE
Can't read yaml for a certain order

### ISSUE THREAD

**Issue by trongbang86** [FasterXML/jackson-dataformats-text#291]
I'm using this
```
<dependency>
  <groupId>com.fasterxml.jackson.dataformat</groupId>
  <artifactId>jackson-dataformat-yaml</artifactId>
  <version>2.10.3</version>
</dependency>
```

When reading from yaml like this:

```
ProjectDetails:
  - Name: abc
    Field: abc

DataClassification: abc
```

It fails to read the field `DataClassification` but it works if I reorder the entries

```
DataClassification: abc

ProjectDetails:
  - Name: abc
    Field: abc
```
Following is what I do in java code

```
    ObjectMapper om = new ObjectMapper(new YAMLFactory());
    Topic topic = om.readValue(file, Topic.class);
```

```
    @JsonProperty("DataClassification")
    public String getDataClassification() {
        return dataClassification;
    }
```

Any suggestions how to fix this pls?
