### ISSUE TITLE
Cannot deserialize YAML sets

### ISSUE THREAD

**Issue by FichteFoll** [FasterXML/jackson-dataformats-text#317]
I was trying to deserialize a mapping of strings to sets and was met with the following error:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.HashSet<java.lang.String>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (BufferedReader); line: 2, column: 4] (through reference chain: java.util.LinkedHashMap["A"])
```

YAML source:
```yaml
# block-style mapping (=set)
A: !!set
  ? A:A
  ? A:B

# flow mapping (=set)
B: !!set {B:A:, B:B:}
```

Simplified test code:
```java
    public Map<String, Set<String>> readConfig(Path path) throws IOException {
        var yamlMapper = new ObjectMapper(new YAMLFactory());
        Map<String, Set<String>> map;
        try (var reader = Files.newBufferedReader(path)) {
            return yamlMapper.readValue(reader, new TypeReference<>() {});
        }
    }
```
