### ISSUE TITLE
yaml writeValueAsString on @JsonSubTypes  fields got unexpected character

### ISSUE THREAD

**Issue by agilests** [FasterXML/jackson-dataformats-text#535]
java interface:

``` java
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        property = "type"
)
@JsonSubTypes({
        @JsonSubTypes.Type(
                value = FieldDescriptor.Text.class,
                name = "text"
        ),
        @JsonSubTypes.Type(
                value = FieldDescriptor.Id.class,
                name = "id"
        )
})
public interface FieldDescriptor{}

public class Id implements FieldDescriptor{}

public class Text implements FieldDescriptor{}
```

java bean: 

``` java
public class Template {
    private String name;
    private Map<String, FieldDescriptor> fields;
}
```

kt example(java has same problem):

``` java

fun test() {

        val template = Template()
        template.name = "test"
        val id = FieldDescriptor.Id()
        id.setComments("id")
        val mobile = FieldDescriptor.Text()
        mobile.setComments("mobile")
        template.fields = mapOf("id" to id, "mobile" to mobile)
        val yml = ObjectMapper(YAMLFactory())
        println(yml.writer().withDefaultPrettyPrinter().writeValueAsString(template))
}

```

Then I got this:

``` yaml
---
name: "test"
fields:
  id: !<id>
    required: false
    origin: "THIRD_PARTY"
    type: "id"
    comments: "id"
  mobile: !<text>
    required: false
    type: "text"
    comments: "mobile"

```

I don't know how to configure to hide `!<id>` and `!<text>`.
