### ISSUE TITLE
Hex number as an entry of an Object causing problem(s) with binding to POJO

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformats-text#71]
It looks as if content like:

```
prop:
  subs:
     more: text
id: 0x1962
```

causes problems due to coercion (or not?) as a hex-number.
